# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cours Programmation Web
email: ms@ms-studio.net
description: > # this means to ignore newlines until "baseurl:"
  Un support de cours pour apprendre la programmation web. <br/>
  Sujets: HTML, CSS, WordPress. <br/>
  Licence: CC-BY-SA.
baseurl: "/cours-web" # the subpath of your site, e.g. /blog
url: "http://collectifwp.github.io" # the base hostname & protocol for your site
repository: cours-web/collectifwp.github.io.
twitter_username: 16kbit
github_username:  ms-studio

# Build settings
markdown: kramdown