# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cours Programmation Web
email: ms@ms-studio.net
description: > # this means to ignore newlines until "baseurl:"
  Un support de cours pour apprendre la programmation web.<br/>
  Sujets: HTML, CSS, JS, WordPress, Git.<br/>
  Licence des contenus: CC-BY-SA.
# baseurl: "/cours-web" # the subpath of your site, e.g. /blog
url: "https://cours-web.ch" # the base hostname & protocol for your site
repository: cours-web/coursweb.github.io.
twitter_username: 16kbit
github_username:  coursweb

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Whitespace killer
compress_html:
  clippings: false
  comments: false
  endings: false
  ignore:
    envs: []
  blanklines: true
  profile: true
  startings: false

# Custom settings

chapters:
 - title: HTML
   url: html
 - title: CSS
   url: css
 - title: Media
   url: media
 - title: Typographie
   url: typographie
 - title: JavaScript
   url: javascript
 - title: WordPress
   url: wp
 - title: Git
   url: git
 - title: Outils
   url: outils
 - title: Figma
   url: figma
 - title: Processus
   url: processus
 - title: Newsletters
   url: newsletters
 - title: Serveurs
   url: serveurs
 - title: Divers
   url: divers


# end of _config.yml
